export const REQUEST_WEATHER_DATA = "REQUEST_WEATHER_DATA";
export const RECEIVE_WEATHER_DATA = "RECEIVE_WEATHER_DATA";

export const RECEIVE_CHANGE_TEMP_SCALE = "RECEIVE_CHANGE_TEMP_SCALE";
export const REQUEST_CHANGE_TEMP_SCALE = "REQUEST_CHANGE_TEMP_SCALE";
